swagger: "2.0"
info:
  version: "0.0.1"
  title: Wave Software Development Challenge API
host: localhost:10010
basePath: /
schemes:
  - http
produces:
  - application/json
paths:
  /v1/payroll/uploadTimeReport:
    x-swagger-router-controller: payroll
    post:
      description: >-
       Upload and parse a time report, and store the timekeeping information in
       a relational database for archival reasons.
       The response returns an application/json object.
      operationId: uploadTimeReport
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: timeReportFile
          in: formData
          type: file
          required: true
          description: The time report to upload.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UploadTimeReportResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /v1/payroll/getPayrollReport:
    x-swagger-router-controller: payroll
    post:
      description: >-
       Get a payroll report. The response returns an array of objects. Each
       object describes how much each employee should be paid in each pay
       period.
      operationId: getPayrollReport
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/getPayrollReportResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      success:
        type: boolean
      message:
        type: string
  UploadTimeReportResponse:
    required:
      - message
    properties:
      success:
        type: boolean
      message:
        type: string
  GetAllImageResponse:
    required:
      - images
    properties:
      success:
        type: boolean
      payrolls:
        type: array
        items:
          type: object
